version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    minijinja:
      patterns:
        - "minijinja*"
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
