name: Build and deploy to Cloudflare Workers

on:
  push:
    branches:
    - master
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v4
    - name: Cache build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          node_modules/
          /usr/share/rust/.rustup/
        key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-
    - uses: dtolnay/rust-toolchain@stable
    - name: Deploy to workers
      env:
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
      run: |
        npm install
        npx wrangler deploy
